name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name tsuzumiragacr123

      - name: Build and Push Docker image
        run: |
          docker build -t tsuzumiragacr123.azurecr.io/tsuzumi-rag-chat:latest .
          docker push tsuzumiragacr123.azurecr.io/tsuzumi-rag-chat:latest

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name tsuzumi-rag-chat \
            --resource-group rg-tsuzumi-chatbot \
            --image tsuzumiragacr123.azurecr.io/tsuzumi-rag-chat:latest
